export const routes = {
  login: "/login",
  forgotPassword: "/forgot-password",
  app: "/app",
  overview: "/app/overview",
  designSystem: "/app/design-system",
  branches: "/app/branches",
  staff: "/app/staff",
  rolesPermissions: "/app/roles-permissions",
  doctorSchedules: "/app/doctor-schedules",
  appointments: "/app/appointments",
  appointmentRequests: "/app/appointment-requests",
  queue: "/app/queue",
  emergencyCheckin: "/app/emergency-checkin",
  clients: "/app/clients",
  pets: "/app/pets",
  consultations: "/app/consultations",
  labDashboard: "/app/lab/dashboard",
  imaging: "/app/imaging",
  pharmacyQueue: "/app/pharmacy/queue",
  inventory: "/app/inventory",
  billing: "/app/billing",
  settings: "/app/settings",
};
